language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" EXCLUDE="account_default_draft_move,account_payment_include_draft_move" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" EXCLUDE="account_default_draft_move,account_payment_include_draft_move" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" INCLUDE="account_payment_include_draft_move" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" INCLUDE="account_payment_include_draft_move" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/account-financial-tools.git ${HOME}/account-financial-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install unidecode
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
